name: NuGet Restore

on:
  workflow_dispatch:  

jobs:
  build:
    name: NuGet@${{ matrix.nuget }} ${{ matrix.os }} sample
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        nuget: [latest, preview, 4.x, 5.3.1]

    steps:
      - name: Get the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: ${{ matrix.nuget }}

      - uses: actions/cache@v4
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore NuGet packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: nuget restore Github.Actions.sln
